/* automatically generated by rust-bindgen 0.69.1 */

pub type YosysDesignPtr = *mut ::std::os::raw::c_void;
extern "C" {
    pub fn yosys_design_new() -> YosysDesignPtr;
}
extern "C" {
    pub fn yosys_design_delete(design_ref: YosysDesignPtr);
}
